# Generated by Django 4.0.4 on 2022-05-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='image',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
        migrations.AddField(
            model_name='cliente',
            name='imagenCli',
            field=models.ImageField(null=True, upload_to='clientes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagenPro',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
