# Generated by Django 4.0.4 on 2022-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0002_remove_cliente_image_remove_producto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='imagenCli',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
