# Generated by Django 4.0.4 on 2022-05-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0003_alter_cliente_direccion_alter_cliente_imagencli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagenCli',
            field=models.ImageField(null=True, upload_to='clientes'),
        ),
    ]
