# Generated by Django 4.0.4 on 2022-06-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0004_alter_cliente_imagencli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagenCli',
            field=models.ImageField(upload_to='clientes'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenPro',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
