# Generated by Django 4.0.4 on 2022-06-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0005_alter_cliente_imagencli_alter_producto_imagenpro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono',
            field=models.IntegerField(null=True, verbose_name='teléfono:'),
        ),
    ]
