# Generated by Django 4.0.4 on 2022-06-26 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0006_cliente_correo_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=60, null=True, verbose_name='E-mail'),
        ),
    ]
