# Generated by Django 4.0.4 on 2022-06-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0007_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
