# Generated by Django 4.0.4 on 2022-07-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0008_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagenCli',
            field=models.ImageField(null=True, upload_to='clientes'),
        ),
    ]
