# Generated by Django 4.0.4 on 2022-07-08 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0010_categoria_producto_id_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id_detalle', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Id Detalle')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_venta',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Id')),
                ('estado', models.CharField(max_length=15, verbose_name='Id')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Id venta')),
                ('total', models.IntegerField(verbose_name='Total')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('cliente_rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfriends.cliente', verbose_name='Rut Cliente')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfriends.estado_venta', verbose_name='Estado')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfriends.venta', verbose_name='Id Venta'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petfriends.producto', verbose_name='Id Producto'),
        ),
    ]
