# Generated by Django 4.0.4 on 2022-07-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0011_detalle_venta_estado_venta_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='cantidad',
            field=models.IntegerField(null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='precioProducto',
            field=models.IntegerField(null=True, verbose_name='Precio Producto'),
        ),
    ]
