# Generated by Django 4.0.4 on 2022-07-13 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0013_alter_estado_venta_estado_delete_detalle_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioProducto', models.IntegerField(null=True, verbose_name='Precio Producto')),
                ('cantidad', models.IntegerField(null=True, verbose_name='Cantidad')),
            ],
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(blank=True, through='petfriends.Detalle_Venta', to='petfriends.producto', verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='id_venta',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='petfriends.venta', verbose_name='Id Venta'),
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='producto',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='petfriends.producto', verbose_name='Id Producto'),
        ),
    ]
