# Generated by Django 4.0.4 on 2022-07-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0014_detalle_venta_venta_productos_detalle_venta_id_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.DeleteModel(
            name='Detalle_Venta',
        ),
    ]
