# Generated by Django 4.0.4 on 2022-07-15 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0015_remove_venta_productos_delete_detalle_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Id')),
                ('estado', models.CharField(max_length=15, verbose_name='Estado')),
            ],
        ),
    ]
