# Generated by Django 4.0.4 on 2022-07-15 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petfriends', '0016_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
